{
    'name': 'cupo',
    'summary': 'gestion de cupones',
    'description': """
     facturas to ordernes .
    """,  
    "depends" : ['base','point_of_sale','portal','product','sale','account'],
    "author" : "ithesk developers",
    "category": 'protf of payment',
    "version":"12.4.3.3",
    "license": 'OPL-1',
    'sequence': 1,
    "email": 'info@ithesk.com',
    "website":'http://ithesk.com/',    
    "data": [
          
          'views/menu.xml',
        # 'views/assent.xml',  
        # 'views/upload.xml', 
        # 'views/error.xml', 
        # 'views/not_found.xml', 
         'security/ir.model.access.csv',
        # 'views/templete_cupon.xml',
         'views/pos_templete.xml',
        #  'views/views.xml',
        # 'views/valid.xml',   
        # 'views/pos_transaction_temp_views.xml', 
        #  'views/not_found.xml',
        'views/formcupon.xml',
    ],
    'qweb': [
        'static/src/xml/templete_cupon.xml',
        'static/src/xml/pos_coupon_ticket.xml',
       # 'static/src/xml/comprobante.xml',
    ],
    "test": [],
    'installable': True,
    'auto_install': False,
    'application': True,
    "images": [],
}
